### ISSUE TITLE
Advanced GUI not working on 1.12 with dev-32 (can't understand condition)

### ISSUE THREAD

**Issue by Tristag** [Tuke-Nuke/TuSKe#20]
Hey! not sure if this is user error but it all worked fine in 1.11.

![image](https://user-images.githubusercontent.com/13598108/32138343-f8374f82-bbfe-11e7-8e65-5ffaf4ada80e.png)

It says "can't understand condition"

**Comment by Iuvaten-de** [comment]
I have the same problem in dev-32.

**Comment by melinstagibson** [comment]
Can confirm

**Comment by melinstagibson** [comment]
This error might be related. i get it on startup with dev32
`[20:45:17 WARN]: [TuSKe] Plugin TuSKe v1.8.2-dev.6 generated an exception while executing task 64
java.lang.NoSuchMethodError: ch.njol.skript.lang.function.Functions.getJavaFunctions()Ljava/lang/Iterable;
        at com.github.tukenuke.tuske.documentation.Documentation.run(Documentation.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1247]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1247]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1247]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by Tuke-Nuke** [comment]
Fixed in last release, thank's for reporting it.
